service: aws-sls-upload-s3
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 128
  timeout: 10
  environment:
    BUCKET_NAME: ${env:S3_BUCKET_NAME, 'your-bucket-name'}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
          Resource: "arn:aws:s3:::${env:S3_BUCKET_NAME, 'your-bucket-name'}/*"

functions:
  index:
    handler: src/functions/index.handler
    events:
      - httpApi:
          method: post
          path: /upload

build:
  esbuild:
    bundle: true
    target: node20
    platform: node
    sourcemap: true
    exclude: ['aws-sdk']
